theme: jekyll-theme-architect
title: Welcome to Devin's Page
description: This is where I showcase the current projects Iam working on.
-How to contact me-
email is the best way to reach me, the following email is one that I have dedicated for professional use. 
devin.landeros@gmail.com 
